var hto_corners = [
'OLRLRLRLOBLGYLYGLBWLWLGLLYLLBLLWLGLBYLYBLGWLWRLOLOLOLR R2 U2 R2 F2',
'OLOLRLRLRBLGYLYBLGWLWLGLLYLLBLLWLBLGYLYBLGWLWOLOLOLRLR B2',
'RLOLRLRLOGLGYLYGLGWLWLGLLYLLBLLWLBLBYLYBLBWLWRLOLOLRLO R2 D2 R2',
'RLOLRLRLOBLGYLWBLGWLYLGLLYLLBLLWLBLGWLYBLGYLWRLOLOLRLO U2 B2 L2',
'OLOLRLRLRBLGYLWGLBYLWLGLLYLLBLLWLBLGYLWGLBYLWOLOLOLRLR R2 B2',
'RLOLRLRLOBLGYLYGLBYLYLGLLYLLBLLWLBLGWLWGLBWLWRLOLOLRLO R2 U2 B2 L2',
'OLOLRLOLOBLBYLYGLGWLWLGLLYLLBLLWLBLBYLYGLGWLWRLRLOLRLR F2 B2',
'OLOLRLOLOGLBYLWBLGWLYLGLLYLLBLLWLBLGWLYGLBYLWRLRLOLRLR R2 F2 L2 U2',
'OLRLRLOLRBLBYLWGLGYLWLGLLYLLBLLWLBLBYLWGLGYLWRLOLOLRLO R2 F2 B2',
'RLRLRLOLOBLBYLYGLGYLYLGLLYLLBLLWLBLBWLWGLGWLWOLOLOLRLR U2 B2 D2'];
