var lang = [
["af","Afrikaans"],
["sq","Albanian"],
["am","Amharic"],
["ar","Arabic"],
["hy","Armenian"],
["as","Assamese"],
["ay","Aymara"],
["az","Azerbaijani"],
["bm","Bambara"],
["eu","Basque"],
["be","Belarusian"],
["bn","Bengali"],
["bho","Bhojpuri"],
["bs","Bosnian"],
["bg","Bulgarian"],
["ca","Catalan"],
["ceb","Cebuano"],
["ny","Chichewa"],
["zh-CN","Chinese (Simplified)"],
["zh-TW","Chinese (Traditional)"],
["co","Corsican"],
["hr","Croatian"],
["cs","Czech"],
["da","Danish"],
["dv","Dhivehi"],
["doi","Dogri"],
["nl","Dutch"],
["en","English"],
["eo","Esperanto"],
["et","Estonian"],
["ee","Ewe"],
["tl","Filipino"],
["fi","Finnish"],
["fr","French"],
["fy","Frisian"],
["gl","Galician"],
["ka","Georgian"],
["de","German"],
["el","Greek"],
["gn","Guarani"],
["gu","Gujarati"],
["ht","Haitian Creole"],
["ha","Hausa"],
["haw","Hawaiian"],
["iw","Hebrew"],
["hi","Hindi"],
["hmn","Hmong"],
["hu","Hungarian"],
["is","Icelandic"],
["ig","Igbo"],
["ilo","Ilocano"],
["id","Indonesian"],
["ga","Irish"],
["it","Italian"],
["ja","Japanese"],
["jw","Javanese"],
["kn","Kannada"],
["kk","Kazakh"],
["km","Khmer"],
["rw","Kinyarwanda"],
["gom","Konkani"],
["ko","Korean"],
["kri","Krio"],
["ku","Kurdish (Kurmanji)"],
["ckb","Kurdish (Sorani)"],
["ky","Kyrgyz"],
["lo","Lao"],
["la","Latin"],
["lv","Latvian"],
["ln","Lingala"],
["lt","Lithuanian"],
["lg","Luganda"],
["lb","Luxembourgish"],
["mk","Macedonian"],
["mai","Maithili"],
["mg","Malagasy"],
["ms","Malay"],
["ml","Malayalam"],
["mt","Maltese"],
["mi","Maori"],
["mr","Marathi"],
["mni-Mtei","Meiteilon (Manipuri)"],
["lus","Mizo"],
["mn","Mongolian"],
["my","Myanmar (Burmese)"],
["ne","Nepali"],
["no","Norwegian"],
["or","Odia (Oriya)"],
["om","Oromo"],
["ps","Pashto"],
["fa","Persian"],
["pl","Polish"],
["pt","Portuguese"],
["pa","Punjabi"],
["qu","Quechua"],
["ro","Romanian"],
["ru","Russian"],
["sm","Samoan"],
["sa","Sanskrit"],
["gd","Scots Gaelic"],
["nso","Sepedi"],
["sr","Serbian"],
["st","Sesotho"],
["sn","Shona"],
["sd","Sindhi"],
["si","Sinhala"],
["sk","Slovak"],
["sl","Slovenian"],
["so","Somali"],
["es","Spanish"],
["su","Sundanese"],
["sw","Swahili"],
["sv","Swedish"],
["tg","Tajik"],
["ta","Tamil"],
["tt","Tatar"],
["te","Telugu"],
["th","Thai"],
["ti","Tigrinya"],
["ts","Tsonga"],
["tr","Turkish"],
["tk","Turkmen"],
["ak","Twi"],
["uk","Ukrainian"],
["ur","Urdu"],
["ug","Uyghur"],
["uz","Uzbek"],
["vi","Vietnamese"],
["cy","Welsh"],
["xh","Xhosa"],
["yi","Yiddish"],
["yo","Yoruba"],
["zu","Zulu"]];
var s = `
<select id=langsel
  style="height:26px; border-radius:15px; padding:0 10px 0; 
         outline:none; border:none; background-color:#ffffff">`;
s += '<option value="00">Select Language</option>';
for (var i=0; i < lang.length; i++)
  s += '<option value=' + lang[i][0] + '>' + lang[i][1] + '</option>';
s += '</select>';
document.getElementById('langdiv').innerHTML = s;
function go() {
  sel = document.getElementById('langsel').value;
  if (sel == '00')
    return;
  var g = 'https://translate.google.com/translate?sl=en&tl=';
  if (location.href.indexOf('gitlab') > 0)
    var u = 'https://mfeather.gitlab.io/3ColorCube';
  else
    var u = 'https://mfeather1.github.io/3ColorCube';
  location =  g + sel + '&u=' + u;
}
